/* UNION, UNION ALL : 합집합 처리
- UNION : 중복데이터는 하나만 선택
- UNION ALL : 모든 데이터를 선책(중복데이터도)
(주의)조회하는 컬럼의 이름, 순서, 갯수, 타입이 일치하도록 작성
**************/
--UNION 사용 예제
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(1, 2, 3);
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(3, 4, 5);
-- UNION으로 합하기 : 중복데이터는 1개만 선택
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(1, 2, 3)
UNION
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(3, 4, 5);
-- UNION ALL 합하기 : 중복데이터(동일데이터) 모두 선택
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(1, 2, 3)
UNION ALL
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(3, 4, 5)
ORDER BY NAME --ORDER BY 절은 마지막에만 사용가능
;

------------------
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(1, 2, 3)
MINUS
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(3, 4, 5);

---------
-- INTERSECT : 교집합 - 조인문중 INNER JOIN
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(1, 2, 3)
INTERSECT
SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN(3, 4, 5);

-- 조인문
SELECT * 
  FROM(SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (1, 2, 3)) A,
      (SELECT CUSTID, NAME FROM CUSTOMER WHERE CUSTID IN (3, 4, 5)) B
 WHERE A.CUSTID = B.CUSTID
   AND A.NAME = B.NAME

